apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
      - name: llm-api-container
        image: jacksonmakl/llm-api:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
          limits:
            memory: "32Gi"
            cpu: "8"
        env:
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-secret
              key: HUGGINGFACE_TOKEN

